export const QUERY_KEY = {
	GET_SEARCH: 'GET_SEARCH',
	GET_POPULAR: 'GET_POPULAR',
	GET_NOW_PLAYING: 'GET_NOW_PLAYING',
	GET_TOP_RATED: 'GET_TOP_RATED',
	GET_DETAIL: 'GET_DETAIL',
	GET_TRAILER: 'GET_TRAILER',
}
