export const QUERY_KEY = {
	GET_SEARCH: 'GET_SEARCH',
	GET_CATEGORY: 'GET_CATEGORY',
	GET_DETAIL: 'GET_DETAIL',
	GET_TRAILER: 'GET_TRAILER',
}
export const INFINITY_QUERY_KEY = {
	GET_IF_POPULAR: 'GET_IF_POPULAR',
	GET_IF_NOW_PLAYING: 'GET_IF_NOW_PLAYING',
	GET_IF_TOP_RATED: 'GET_IF_TOP_RATED',
	GET_IF_UPCOMING: 'GET_IF_UPCOMING',
}
